---
 - name: Install gnupg2 curl software-properties-common
   apt:
    update_cache: yes
    name: "{{ item }}"
   loop:
   - gnupg2
   - curl
   - software-properties-common

 - name: Download GPG key
   ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

 - name: Add grafana repository into sources list
   ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

 - name: Install grafana
   apt:
    update_cache: yes
    name: grafana

 - name: Configure Datasource
   template:
    src: datasource.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yaml

 - name: copy prometheus dashboard
   copy:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml

 - name: copy prometheus dashboard
   copy:
    src: prometheus-dashboard.json
    dest: /etc/grafana/provisioning/dashboards

 - name: Enable grafana-server
   systemd:
    name: grafana-server
    enabled: yes
    state: started