---
 - name: Install gnupg2 curl software-properties-common
   apt:
    update_cache: yes
    name: "{{ item }}"
   loop:
   - gnupg2
   - curl
   - software-properties-common

 - name: Download GPG key
   ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

 - name: Add grafana repository into sources list
   ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

 - name: Install grafana
   apt:
    update_cache: yes
    name: grafana

 - name: Enable grafana-server
   systemd:
    name: grafana-server
    enabled: yes
    state: started