-
  hosts: consul_servers
  become: yes
  roles:
    - consul_server
    - node_exporter
    - filebeat
  vars:
    ansible_ssh_user: ubuntu
-
  hosts: jenkins_agents
  become: yes
  roles:
    - jenkins_agent
    - consul_agent
    - helm
    - node_exporter
    - filebeat
  vars:
    ansible_ssh_user: ubuntu

-
  hosts: grafana
  become: yes
  roles:
    - consul_agent
    - grafana
    - filebeat
  vars:
    ansible_ssh_user: ubuntu

-
  hosts: prometheus
  become: yes
  roles:
    - consul_agent
    - prometheus
    - filebeat
  vars:
    ansible_ssh_user: ubuntu
    
-
  hosts: jenkins_server
  become: yes
  roles:
    - jenkins_server
    - filebeat
    - consul_agent
  vars:
    ansible_ssh_user: ubuntu

-
  hosts: elastic
  become: yes
  roles:
    - consul_agent
    - elastic-kibana
  vars:
    ansible_ssh_user: ubuntu
    
-
  hosts: Database
  become: yes
  roles:
    - filebeat
    - consul_agent
    - database
  vars:
    ansible_ssh_user: ubuntu
