---
 - name: Download GPG key
   ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

 - name: Install apt-transport-https
   apt:
    update_cache: yes
    name: apt-transport-https

 - name: Add helm repository into sources list
   ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

 - name: Install helm
   apt:
    update_cache: yes
    name: helm
